// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopOnline2022.Models
{
    [Table("AccountCategory")]
    public partial class AccountCategory
    {
        public AccountCategory()
        {
            Accounts = new HashSet<Account>();
        }

        [Key]
        [StringLength(50)]
        public string AccountCategoryID { get; set; }
        [StringLength(50)]
        public string Title { get; set; }
        public bool? Status { get; set; }

        [InverseProperty("AccountCategory")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}