// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopOnline2022.Models
{
    [Table("Article")]
    public partial class Article
    {
        [Key]
        public int ArticleID { get; set; }
        [StringLength(255)]
        public string Avatar { get; set; }
        [StringLength(255)]
        public string Thumb { get; set; }
        [StringLength(255)]
        public string Title { get; set; }
        [StringLength(4000)]
        public string Description { get; set; }
        [Column(TypeName = "ntext")]
        public string Content { get; set; }
        public int? Position { get; set; }
        public bool? Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public int? ArticleCategoryID { get; set; }
        [StringLength(50)]
        public string CreateBy { get; set; }

        [ForeignKey("ArticleCategoryID")]
        [InverseProperty("Articles")]
        public virtual ArticleCategory ArticleCategory { get; set; }
        [ForeignKey("CreateBy")]
        [InverseProperty("Articles")]
        public virtual Account CreateByNavigation { get; set; }
    }
}