// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopOnline2022.Models
{
    [Table("ProductVote")]
    public partial class ProductVote
    {
        [Key]
        public int ClientID { get; set; }
        [Key]
        public int ProductID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTime { get; set; }
        public int? Value { get; set; }

        [ForeignKey("ClientID")]
        [InverseProperty("ProductVotes")]
        public virtual Client Client { get; set; }
        [ForeignKey("ProductID")]
        [InverseProperty("ProductVotes")]
        public virtual Product Product { get; set; }
    }
}